### ISSUE TITLE
5.0beta2 is not working properly on M1 Max Macbook Pro

### ISSUE THREAD

**Issue by blacklein** [Vaida12345/waifuExtension#11]
**Describe the bug**
Everything is normal from importing the model to processing, but after processing, there is no result that should be output in the output folder. The same problem also exists in the previous version.

**To Reproduce**
- Image Model - Real ESRGAN model

**Attachments**
![Kapture 2022-07-05 at 11 55 08](https://user-images.githubusercontent.com/69177971/177246915-5fab603a-bc44-4928-b4dd-6bf8fec6e1c5.gif)

**Additional context**
Since other models are rarely used at ordinary times, whether other models also have the same problem has not been tested.

**A little suggestion**
Although the built-in model will cause the application size to be too large, I hope the release page has a full version of all built-in models and a lightweight version without built-in models, two versions to choose. I personally think that compared with not using this application well, the application size may be not the most important problem to me.

**Comment by blacklein** [comment]
built-in model may cause app very large, but it maybe better to give a large size but "full version" of release, maybe less issues caused by different users, devices, masOSs

**Comment by Vaida12345** [comment]
That's a good idea, I may work on that.

**Comment by Vaida12345** [comment]
I believe the error is caused by the fact that this model would not work(?).

**Comment by blacklein** [comment]
em but i am quite sure the model works after `chmod u+x ./realesrgan-ncnn-vulkan` and i left folder name same as orginal zip filename just like you said in the last issue post. Every step just follows the guide, but not work for me, don't know why.

**Comment by Vaida12345** [comment]
Can you give the new version a try please? It should be fine now.

**Comment by blacklein** [comment]
5.0beta4 can output the enlarged image normally！It works！Thanks a lot！

I hope you don't think I'm picky. I found something not serious but slightly strange. When I use the same model and same picture to enlarge through the terminal and this app, some strange phenomena happen.

The terminal takes 14 seconds, while the application takes 35 seconds to finish job. The image volume output by the terminal is larger than that output by the application. The image format is .png in and .png out. So I guess it's not caused by converting the image format.

For me, this difference is not important. The application provides a better user experience. I am very grateful to this project and the author. Also as a Mac user, it is a big pleasure to see an excellent application born!

![Kapture 2022-07-07 at 14 25 14](https://user-images.githubusercontent.com/69177971/177708795-9405565e-ef27-4de4-9dcc-3ba1a590dac7.gif)
![Kapture 2022-07-07 at 14 27 27](https://user-images.githubusercontent.com/69177971/177708856-9bacd36a-ca62-45ca-addf-327269cad08c.gif)
<img width="798" alt="截屏2022-07-07 14 30 10" src="https://user-images.githubusercontent.com/69177971/177708876-3b089e9d-5f1d-427e-9ffe-3d916df677fb.png">

**Comment by Vaida12345** [comment]
That's really odd. I certainly will look into that later.

**Comment by Vaida12345** [comment]
Sorry but I cannot reproduce this issue on my machine. My suspicion is that your commands in the terminal differs from what the app asks terminal to do. For example, in your gif, the app set TTA to true (equivalent to `-x`), but your commands did not.

**Comment by blacklein** [comment]
Don't be sorry, it is my mistake. The problem is solved. As you said, it is caused by inconsistent options. When I set TTA to false in the app, terminal and app give the same result now.

Excuse me, what does TTA do?
