### ISSUE TITLE
Missing Support Framework

### ISSUE THREAD

**Issue by StevenSK-king** [Vaida12345/waifuExtension#13]
**Describe the bug**
When running the Xcode project, it says: ~/waifuExtension/waifuExtension.xcodeproj Missing package product 'Support'

Where could I find the Support framework or library?

**Comment by Vaida12345** [comment]
Sorry, but that framework is developed by myself and will not be published. If you find anything improper about this project, you can ask me to have it fixed.

**Comment by StevenSK-king** [comment]
> Sorry, but that framework is developed by myself and will not be published. If you find anything improper about this project, you can ask me to have it fixed.

Thanks for the reply. I am trying to use the complied command lines of the models but have this problem, may I ask how do you fix it?
`flock failed to lock list file (/var/folders/jb/0yw0kvrd1_v71gfrz0qxs0m80000gn/C/com.xxx.xxx//com.apple.metal/16777235_530/functions.list): errno = 35`

**Comment by Vaida12345** [comment]
If you want to use models other than Waifu2x, you can use the executable from the authors.
If you only need Waifu2x, you can refer to `/WaifuExtensionCore/Models/Waifu2x/Waifu2x Core/Waifu2x.swift`. Or, you can refer to [imxieyi's work](https://github.com/imxieyi/waifu2x-ios).

**Comment by StevenSK-king** [comment]
> If you want to use models other than Waifu2x, you can use the executable from the authors. If you only need Waifu2x, you can refer to `/WaifuExtensionCore/Models/Waifu2x/Waifu2x Core/Waifu2x.swift`. Or, you can refer to [imxieyi's work](https://github.com/imxieyi/waifu2x-ios).

Thanks about this. I want to use the other models. I create a Xcode project and write code to use the executable command line directly, but it says the `flock failed to lock list file` . I have no idea to fix it.

**Comment by Vaida12345** [comment]
sorry but I did not encounter such problem. If you go to `/waifuExtension/WaifuExtensionCore/Models/InstalledModels/InstalledModels.swift`, You can see how I did to call the executable. For further questions I would suggest to ask Google or Stackoverflow instead. I will close this issue.

**Comment by StevenSK-king** [comment]
Thanks. I will try it again. Good day!
