### ISSUE TITLE
Added models don't show up available list

### ISSUE THREAD

**Issue by NicolasSompairac** [Vaida12345/waifuExtension#17]
Hi there,

I have tried the models included by default in the App and it worked without problem.
I then decided to add the 3 other models listed in preferences: I downloaded the releases containing the excecutables and added them into the App in /Content/Ressources.

The models were marked as imported I guess since the check mark showed ✓.
However, when upscaling an image, only the 4 default ones are shown and I don't see the 3 new ones (CAIN, DAIN, RIFE).

**Comment by Vaida12345** [comment]
The three models you added are used to add frames, which only works with videos and when “Enable video frame interpolation” and processing a video. Note that all the four enlarge models were included since 5.0
