### ISSUE TITLE
wish add realesrgan-ncnn-vulkan model in the app

### ISSUE THREAD

**Issue by blacklein** [Vaida12345/waifuExtension#2]
wish add realesrgan-ncnn-vulkan model in the app

**Comment by Vaida12345** [comment]
Thank you for your advice, It has been added, please download the latest version from [releases](https://github.com/Vaida12345/waifuExtension/releases)
Please inform me if you encounter any bug.

**Comment by blacklein** [comment]
Thank you very much for your reply, but there may be some misunderstandings. I hope you can add the following model to the app instead of RealSR one.

https://github.com/xinntao/Real-ESRGAN

This app is the most beautiful and useful of the open source and non open source software for macOS I found on the Internet. Thank you very much for your outstanding work, whether you add the above model or not.

**Comment by blacklein** [comment]
By the way, I tested RealSR and Real-ESRGAN with the binary unix app of the open source project. Real-ESRGAN has better performance in the magnification effect of animation images, far way better. That's why I hope you can adopt Real-ESRGAN.
The following is the original picture：
![f43b4bc630461764aa4ff030c709a468](https://user-images.githubusercontent.com/69177971/158288347-2f476d0e-31cd-4cb7-a4ef-eb4fac013459.jpeg)

The following is a 4x scale magnification comparison of RealSR(left) and Real-ESRGAN(right) by Kaleidoscope.app:
![compare](https://user-images.githubusercontent.com/69177971/158289302-12d00ba5-196c-44a8-99bb-9a8ccdac72b9.jpg)

**Comment by Vaida12345** [comment]
Working on that, thank you for your suggestions.

**Comment by Vaida12345** [comment]
Done, check https://github.com/Vaida12345/waifuExtension/releases/tag/v4.0.1

**Comment by blacklein** [comment]
The new release comes too fast. Thank you very much for your incredible work！
The app size is quite large but this won't be a problem to me. The function of the app has been greatly improved, and the interactive design is also very intuitive and easy to use. 
As far as I know, this app is the only macOS app supporting Real-ESRGAN model and written in Swifty language，that can be found on the Internet at present. The actual test results are outstanding. It's really great!
Wow it supports animation video too！？My Macbook is made of Intel chip. It takes several hours to process a video. I'm so curious about how long it will take Apple M1 chip to process a 200 megabyte video？

**Comment by Vaida12345** [comment]
If you use waifs2x_Caffe, it would be pretty fast, my M1Max took only ~0.7s to process a 1080p image. But other models are quite slow, as I just used their complied executable file, which do not use the Apple Neural Engine.

**Comment by Vaida12345** [comment]
Thank you for using this app!

**Comment by blacklein** [comment]
I recommended your open source projects in the excellent software discussion forum I often go to. Your excellent works should be known by more people, especially on the isolated island of MacOS. Thank you for your outstanding work!
