### ISSUE TITLE
[Reminder] Don't use MIT license for a complete app

### ISSUE THREAD

**Issue by imxieyi** [Vaida12345/waifuExtension#3]
I'm the author of [waifu2x-mac](https://github.com/imxieyi/waifu2x-mac). I worked on this project back in 2017 but stopped later. Guess why? I also used MIT license and someone took my code and published the app almost as-is on the Mac App Store and charged for $3 ([archived page](https://archive.md/d9Nhp)). I'm not gonna to work on a project and let some random person make free money out of it.

If you are building a full app and publish under MIT license, it's almost guaranteed that someone will do the same and publish your app to MAS without even modifying the UI, then charge a premium. And it can be even worse: they can add much more features to the app and do not contribute a single line of code back to your project.

If you are not going to publish this app to MAS by yourself, please use GPL license.

In any case, if you don't feel like working for some random person for free and let them take all the income, please avoid MIT license.

**Comment by Vaida12345** [comment]
Thank you for your advice! And thank you for your great work! My codes for Waifu2x Caffe were basically your code.

**Comment by imxieyi** [comment]
I saw that you changed the license to GPL. Please keep in mind that there will be a lot of people who don't care about license at all and will publish to MAS anyway. Reviewers of MAS will not check compliance of license. For example, [IINA](https://github.com/iina/iina), which is licensed under GPL, had been published by many different people to MAS over the years. GPL only gives you the weapon to appeal to Apple and take down those apps. But still, it's way better than MIT which does not give you any valid reason to take down apps.

**Comment by Vaida12345** [comment]
Will keep that in mind, thank you!
