### ISSUE TITLE
Various crashes

### ISSUE THREAD

**Issue by sclsj** [Vaida12345/waifuExtension#6]
I have no idea why they happened and don't have the time to reproduce as they occur 1~3 hours into an operation. By the way, is there a way to recover/resume a session?
[waifuextension crash.zip](https://github.com/Vaida12345/waifuExtension/files/8347424/waifuextension.crash.zip)

**Comment by Vaida12345** [comment]
Can you send me the video you tried to process and the operations used? I will try to reproduce the error. 
When processing videos (enlarging videos), if an image already exists at the temp location, the app would skip the part and continue to the next one.

**Comment by Vaida12345** [comment]
btw, which model are you using? I simply used the executable files for models except for Waifu2x, these models uses gpu instead of ANE to calculate, which is why they are terribly slow.

**Comment by sclsj** [comment]
https://scls-my.sharepoint.cn/personal/joyjin_scls-sh_org/_layouts/15/guestaccess.aspx?docid=0d473636bfb2e420b829efd5890f6723e&authkey=AUML2BqmNbkujEgnDLwMN9s&e=gVkHTD
Please tell me when you have downloaded the video.

**Comment by sclsj** [comment]
waifu
2x
no denoise (0)
no interlace

**Comment by sclsj** [comment]
I'm trying to reproduce the error on a smaller clip and noticed the large ETA. Is this normal
<img width="1012" alt="截屏2022-03-26 21 55 14" src="https://user-images.githubusercontent.com/38654636/160242655-1155b01b-af13-4fc8-9680-be602f09057b.png">
?

**Comment by Vaida12345** [comment]
> I'm trying to reproduce the error on a smaller clip and noticed the large ETA. Is this normal
> <img alt="截屏2022-03-26 21 55 14" width="1012" src="https://user-images.githubusercontent.com/38654636/160242655-1155b01b-af13-4fc8-9680-be602f09057b.png">
> ?

It meant the time it would finish.

**Comment by Vaida12345** [comment]
> https://scls-my.sharepoint.cn/personal/joyjin_scls-sh_org/_layouts/15/guestaccess.aspx?docid=0d473636bfb2e420b829efd5890f6723e&authkey=AUML2BqmNbkujEgnDLwMN9s&e=gVkHTD
> Please tell me when you have downloaded the video.

Downloaded, thank you.

**Comment by Vaida12345** [comment]
I failed to reproduce your error. Maybe the new version works fine, please inform me if you find any other issues.

**Comment by sclsj** [comment]
I tried again and can reproduce the error. I think it's a certain segment of the video (I think #6) that triggered the fault. I will see if I can reproduce the error again using this shorter segment or another video.
[waifuExtension-2022-03-27-121447.ips.zip](https://github.com/Vaida12345/waifuExtension/files/8357005/waifuExtension-2022-03-27-121447.ips.zip)

**Comment by sclsj** [comment]
Sorry, I'm using the old version. Let me try the new version and see if I can reproduce the error.

**Comment by sclsj** [comment]
I can confirm that this no longer occurs with the new version.

**Comment by Vaida12345** [comment]
Great, Thanks!
