### ISSUE TITLE
Miss support files 

### ISSUE THREAD

**Issue by milawoai** [Vaida12345/waifuExtension#8]
**Describe the bug**
 The project depend on relative path "../../Swift/testRoom/testRoom/Source/Support"  and XCode reports "Build input files cannot be found", should those files be upload please 😁

**To Reproduce**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/7558294/161949671-c6dbebdc-5f2d-4bb4-866a-db2539238933.png">

**Comment by Vaida12345** [comment]
[Support.zip](https://github.com/Vaida12345/waifuExtension/files/8456920/Support.zip)
I keep updating files inside this folder, please modify it if needed.
