### ISSUE TITLE
Ver 4.1.3 App is not functioning properly after Real-ESRGAN model update

### ISSUE THREAD

**Issue by blacklein** [Vaida12345/waifuExtension#9]
**Macbook Pro M1 Max**

**Describe the bug**
<img width="912" alt="000" src="https://user-images.githubusercontent.com/69177971/176394512-19920f42-e39a-4323-bd04-5ec628adfcff.png">
<img width="1012" alt="444" src="https://user-images.githubusercontent.com/69177971/176394537-22ce93ff-c3fa-404b-b812-0dd82109737d.png">
<img width="1012" alt="555" src="https://user-images.githubusercontent.com/69177971/176394584-3bc128ec-05d8-41ec-acbb-3c5902f953c5.png">
The Real-ESRGAN model has been loaded successfully, the Model Manager status is displayed as true, but the application fails to run, and none of images to be processed.

**To Reproduce**
I used the model linked below.
https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-macos.zip

However, if I change back to the old version of the model in the link below, the application will work properly.
https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.3.0/realesrgan-ncnn-vulkan-20211212-macos.zip

**Suggestion**
<img width="1012" alt="666" src="https://user-images.githubusercontent.com/69177971/176396020-d7430717-e773-4406-bd23-7d32ae8d7241.png">
The 'Time Remaining' and 'ETA' have never been accurate, sometimes cause crash, and the progress bar blow ‘ETA' has never accurately expressed the actual processing progress. It is recommended to remove these items.
![222](https://user-images.githubusercontent.com/69177971/176397126-7c1d5817-1a73-4330-9524-c2bc28e2a44b.gif)
When the portable binary of the Real-ESRGAN model runs, the completion percentage will be displayed. I would suggest to display this percentage，or the progress bar (or other chart) created by these percentages in the app.

**Looking forward to the next update of the app. Thank you.**

**Comment by Vaida12345** [comment]
Please include the folder containing the realsrgan-ncnn-vulkan. The executable file alone would not work.

**Comment by blacklein** [comment]
model manager is ‘true’, but no output image in ‘Waifu Output’ folder. The model has updated after v4.1.3 release, maybe the reason of not working anymore.

**Comment by Vaida12345** [comment]
Thank you for your bugs report. I will work on that. 
The temporary workaround might be converting your image into another format, say `.png`. HEIC would not work for models other than Waifu2x.

**Comment by blacklein** [comment]
Improved the issue description and added a suggestion.

Looking forward to the next update of the app. Thank you.

**Comment by Vaida12345** [comment]
The waifu2x should be the fastest, as it uses Neural Engine to accelerate the process. The other models uses only GPU.

**Comment by Vaida12345** [comment]
Thank you for your suggestions! I sure will look into that. Can you provide me with the image you used please?

**Comment by blacklein** [comment]
Sure, do you mean this one?
![Untitled 4](https://user-images.githubusercontent.com/69177971/176404176-82bc5831-ca60-4297-b1e0-e39ffc411e80.png)
